### ISSUE TITLE
NWP-F120 Pin

### ISSUE THREAD

**Issue by SebMIL** [NeoSmartpen/UWPSDK#1]
Hi!

I recently got two NWP-F120 pens and am now trying to work with them and the SDK.
When I try to pair/connect to the pens from my Windows 10 PC, I am asked for a PIN. Unfortunatly there was no documentation included with the pens and so I do not know the correct PIN. When I try the standard Bluetooth-PIN's "0000" and "1234" I get an AuthenticationTimeout as result from the PairAsync call in the Pairing Method. 
When using the pens with my Android phone and the Neonotes app I can successfully pair the pen (without providing a PIN) and use them with the provided notebooks.

**Comment by SebMIL** [comment]
After trying to connect with a few different Bluetooth adapters I found one which allows me to pair the pen without a prompt for a PIN. So for me the issue is solved!

**Comment by nlc-jychoi** [comment]
@SebMIL  First UWP sdk require Bluetooth Adapter version 2.1 + EDR. And if you use Bluetooth adapter less than version 2.1 + EDR than you must enter the PIN code. 
Actually Neo smartpen's Bluetooth-PIN's default password is "0000". Unfortunately now that was not implemented. so we will add this feature in next firmware release version. But we do not recommend what use less than verseion 2.1 +EDR in UWP SDK. 

thank you
