### ISSUE TITLE
Neo Pen Connectivity And Device Searching Module

### ISSUE THREAD

**Issue by BhupatsinhRathod** [NeoSmartpen/UWPSDK#3]
In your NeoPen connectivity and watcher service used AEP service class IDs.
AEP Service class contains two types of connectivity protocols.
1. Bluetooth  services
2. Bluetooth LE services

you have used  Bluetooth  services for NeoPen connectivity and watcher process.
Why Not Use Bluetooth LE services In Neo Connection Process and watcher process?

please reply for clarification.

**Comment by chyccs** [comment]
SDK using BLE is under development. 
Currently, the structure is designed so that it can be extended to SDK that can use BLE.

**Comment by BhupatsinhRathod** [comment]
How much time it will take for new SDK using BLE??
Because we require this feature in our client app.

Please reply ..

**Comment by chyccs** [comment]
I wonder if the purpose is commercial or non-commercial.
For commercial use, please contact our business team.
(See the license section of the readme)
We have not yet decided whether to public release the SDK for BLE.
